### ISSUE TITLE
Duplicated functions in testing_deployment.py

### ISSUE THREAD

**Issue by NoelieRamuzat** [olivier-stasse/robotpkg_helpers#6]
In `testing_deployment.py` at line 458 you call `self.execute_call(bashcmd)`, calling the `self.logger.execute_call` _RobotpkghLogging_ method which doesn't exist. 
You have created two functions (`execute` and `execute_call`) calling `execute` and `execute_call` on the logger, but only the execute method exists. 
I think you forgot to delete `execute_call`.
I replace `execute_call` by `execute` at line 458 and everything seems to be fine.

**Comment by olivier-stasse** [comment]
Dear @NoelieRamuzat ,
Commit 4efd1b5d9a96473e8e979f49e19575b38dedd0f1 should fix this.
execute_call is normally used for quiet bash commands.
Could you tell me if this works for you and if it does close the issue ?

**Comment by NoelieRamuzat** [comment]
Yes commit [4efd1b5](https://github.com/olivier-stasse/robotpkg_helpers/commit/4efd1b5d9a96473e8e979f49e19575b38dedd0f1) fixes the issue thanks !
